#!/usr/bin/env bash
# Render app/.env from `terraform output` for local development.
#
# Overwrites app/.env with values pulled from the terraform state. Anything
# below the "# --- local overrides ---" marker line in the existing file is
# preserved so users can keep local-only settings (e.g. LOG_LEVEL=debug).

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TERRAFORM_DIR="${REPO_ROOT}/terraform"
ENV_FILE="${REPO_ROOT}/app/.env"
OVERRIDE_MARKER="# --- local overrides ---"

for cmd in terraform jq; do
  command -v "$cmd" >/dev/null || { echo "missing required tool: $cmd" >&2; exit 1; }
done

TF_JSON="$(cd "$TERRAFORM_DIR" && terraform output -json)"

read_output() {
  local key="$1"
  local val
  val=$(jq -r --arg k "$key" '.[$k].value // empty' <<<"$TF_JSON")
  [[ -n "$val" ]] || { echo "terraform output '$key' missing — run 'terraform apply' first" >&2; exit 1; }
  printf '%s' "$val"
}

PROFILE=$(read_output databricks_profile)
KA_ENDPOINT=$(read_output ka_endpoint_name)
LAKEBASE_HOST=$(read_output lakebase_host)
LAKEBASE_DB=$(read_output lakebase_database_name)
LAKEBASE_EP=$(read_output lakebase_endpoint_path)
MLFLOW_EXP=$(read_output mlflow_experiment_path)

# Preserve local overrides from any previous .env.
OVERRIDES=""
if [[ -f "$ENV_FILE" ]] && grep -qF "$OVERRIDE_MARKER" "$ENV_FILE"; then
  OVERRIDES=$(awk -v m="$OVERRIDE_MARKER" 'found; $0==m{found=1; print}' "$ENV_FILE")
fi

{
  echo "# Auto-generated by scripts/render-env.sh — do not edit values above"
  echo "# the override marker. Re-run with: make render-env"
  echo "DATABRICKS_CONFIG_PROFILE=${PROFILE}"
  echo "GEEC_ASSISTANT_KA_ENDPOINT=${KA_ENDPOINT}"
  echo "GEEC_ASSISTANT_LAKEBASE_HOST=${LAKEBASE_HOST}"
  echo "GEEC_ASSISTANT_LAKEBASE_DATABASE=${LAKEBASE_DB}"
  echo "GEEC_ASSISTANT_LAKEBASE_ENDPOINT=${LAKEBASE_EP}"
  echo "GEEC_ASSISTANT_MLFLOW_EXPERIMENT=${MLFLOW_EXP}"
  if [[ -n "$OVERRIDES" ]]; then
    echo
    echo "$OVERRIDES"
  else
    echo
    echo "$OVERRIDE_MARKER"
    echo "# Add any local-only settings below this line; they are preserved across re-runs."
  fi
} > "$ENV_FILE"

echo "Rendered $ENV_FILE"
